# -*- coding: utf-8 -*-
"""Errore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVE61H5a9I_REmy5I0l9J4mDyW_zmrr9
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity as ssim
from skimage.metrics import peak_signal_noise_ratio
import math

# ==========================================================
# FUNZIONE: LETTURA IMMAGINE DA FILE TXT
# ==========================================================
def read_image(file_path, expected_size=4096):
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File non trovato: {file_path}")

    with open(file_path, 'r') as file:
        data_array = np.loadtxt(file)

    if data_array.size != expected_size:
        raise ValueError(f"Il file {file_path} contiene {data_array.size} valori invece di {expected_size}.")

    # Ridimensionamento del vettore 1D in matrice 2D 64x64
    data = data_array.reshape((64, 64))
    print(f'Immagine caricata: {data.shape}')
    return data

# ==========================================================
# FUNZIONE: CONVOLUZIONE 2D CON ZERO PADDING
# ==========================================================
def convolve2d(image, kernel):
    """
    Applica una convoluzione 2D con kernel 3x3 e zero padding.
    """
    # Flip del kernel (convoluzione matematica)
    kernel = np.flipud(np.fliplr(kernel))

    # Output inizializzato a zero
    output = np.zeros_like(image, dtype=np.float32)

    # Zero padding sui bordi
    image_padded = np.pad(image, pad_width=1, mode='constant', constant_values=0)

    # Scansione pixel per pixel
    for y in range(image.shape[0]):
        for x in range(image.shape[1]):
            region = image_padded[y:y+3, x:x+3]
            output[y, x] = np.sum(region * kernel)

    return output

# ==========================================================
# CONFIGURAZIONE KERNEL
# ==========================================================
# Kernel Gaussiano (Blur, somma pesi = 16)
KERNEL_GAUSSIAN = (1/16) * np.array([
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]
])

# Kernel Laplaciano
KERNEL_LAPLACIANO2 = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

# Kernel Sharpening
KERNEL_SHARPENING = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
])

CURRENT_KERNEL = KERNEL_SHARPENING

# ==========================================================
# PERCORSI FILE
# ==========================================================
input_file_path  = '/content/sample_data/lena64.txt'
output_file_path = '/content/sample_data/outputLena64.txt'
file_path_VHDL = '/content/sample_data/outputLena64sharpening.txt'

# ==========================================================
# ESECUZIONE PRINCIPALE
# ==========================================================
# Caricamento immagine originale
input_image = read_image(input_file_path)

# Applicazione convoluzione
filtered_image_full = convolve2d(input_image, CURRENT_KERNEL)

# Saturazione a 0-255 per output unsigned
filtered_image = np.clip(filtered_image_full, 0, 255).astype(np.uint8)

# Salvataggio output su file di testo
np.savetxt(output_file_path, filtered_image.flatten(), fmt='%d')

# Caricamento immagine filtrata con VHDL
reload_image = read_image(file_path_VHDL)

# ==========================================================
# VISUALIZZAZIONE INIZIALE (3 subplot)
# ==========================================================
plt.figure(figsize=(18, 6))

# Immagine originale
plt.subplot(1, 3, 1)
plt.imshow(input_image, cmap='gray', vmin=0, vmax=255)
plt.title("Immagine Originale")
plt.colorbar(fraction=0.046, pad=0.04)

# Immagine filtrata (calcolata in Python)
plt.subplot(1, 3, 2)
plt.imshow(filtered_image, cmap='gray', vmin=0, vmax=255)
plt.title("Immagine Filtrata (Python)")
plt.colorbar(fraction=0.046, pad=0.04)

# Immagine ricaricata dal file TXT
plt.subplot(1, 3, 3)
plt.imshow(reload_image, cmap='gray', vmin=0, vmax=255)
plt.title("Immagine Filtrata (VHDL)")
plt.colorbar(fraction=0.046, pad=0.04)

plt.tight_layout()
plt.show()

# ==========================================================
# CALCOLO ERRORE ASSOLUTO
# ==========================================================
def ErroreAssoluto(file_path1, file_path2, output_file='errore_assoluto.txt', show_plot=True):
    img1 = read_image(file_path1)
    img2 = read_image(file_path2)
    errore_assoluto = np.abs(img1 - img2)
    np.savetxt(output_file, errore_assoluto.flatten(), fmt='%d')
    print(f'Errore assoluto salvato in: {output_file}')
    if show_plot:
        plt.figure(figsize=(8, 6))
        plt.imshow(errore_assoluto, cmap='viridis', vmin=0, vmax=500)
        plt.colorbar(label='Differenza Assoluta (pixel value)')
        plt.title('Mappa Errore Assoluto |Img1 - Img2|')
        plt.axis('off')
        plt.figtext(0.5, 0.02,
                    'Legenda: Viola = Coincidenza (errore 0), Giallo = Differenze alte (fino a 500)',
                    ha='center', fontsize=10, style='italic')
        plt.savefig('errore_assoluto_plot.png')
        plt.show()
        print('Grafico dell\'errore assoluto salvato come: errore_assoluto_plot.png')
    return errore_assoluto

# Chiama la funzione con i percorsi corretti
errore = ErroreAssoluto(output_file_path, file_path_VHDL)
print(f'Dimensione errore: {errore.shape}')
print(f'Media errore assoluto: {np.mean(errore)}')

# Se media è 0.0, conferma che le immagini sono identiche
if np.mean(errore) == 0.0:
    print("Le immagini sono perfettamente identiche (bit-true). La mappa errore è tutta viola (coincidenza).")

# ==========================================================
# VARIABILI GLOBALI PER METRICHE
# ==========================================================
gray_scale_image_matrix = None  # Immagine originale (caricata da file TXT)
filtered_image_project = None   # Immagine filtrata (caricata da file TXT)

# ==========================================================
# FUNZIONE: CALCOLO SSIM E DSSIM
# ==========================================================
def ssim_calculation():
    """
    Questa funzione calcola i parametri relativi alla Structural Similarity.
    """
    global gray_scale_image_matrix
    global filtered_image_project

    if gray_scale_image_matrix is None or filtered_image_project is None:
        raise ValueError("Immagini non caricate. Chiama main_visualization prima.")

    # Calcolo SSIM
    ssimval, ssimmap = ssim(gray_scale_image_matrix, filtered_image_project, data_range=255, full=True)

    # Visualizzazione (subplot 2x2)
    plt.subplot(2, 2, 3)
    plt.imshow(ssimmap, cmap='gray')
    plt.title(f"SSIM Value: {ssimval:.4f}")
    plt.colorbar()

    # Calcolo DSSIM
    dssimval = (1 - ssimval) / 2
    dssimmap = (1 - ssimmap) / 2

    plt.subplot(2, 2, 4)
    plt.imshow(dssimmap, cmap='gray')
    #DSSIM Map with Global
    plt.title(f"DSSIM Value: {dssimval:.4f}")
    plt.colorbar()

    return ssimval, ssimmap, dssimval, dssimmap

# ==========================================================
# FUNZIONE: CALCOLO PSNR E SNR
# ==========================================================
def psnr_calculation():
    """
    Questa funzione calcola i parametri relativi al Peak Signal-to-Noise-Ratio.
    """
    global gray_scale_image_matrix
    global filtered_image_project

    if gray_scale_image_matrix is None or filtered_image_project is None:
        raise ValueError("Immagini non caricate. Chiama main_visualization prima.")

    # Calcolo PSNR
    psnr_i_f = peak_signal_noise_ratio(gray_scale_image_matrix, filtered_image_project, data_range=255)

    # Calcolo SNR manuale (basato su varianza segnale e rumore)
    signal_var = np.var(gray_scale_image_matrix.astype(float))
    noise_var = np.var((gray_scale_image_matrix - filtered_image_project).astype(float))
    if noise_var == 0:
        snr_i_f = float('inf')  # Evita divisione per zero
    else:
        snr_i_f = 10 * math.log10(signal_var / noise_var)

    # Visualizzazione (subplot 2x2)
    plt.subplot(2, 2, 2)
    plt.imshow(filtered_image_project, cmap='gray', vmin=0, vmax=255)
    plt.title(f"peaksnr: {psnr_i_f:.2f}, snr: {snr_i_f:.2f}")
    plt.colorbar()

    return psnr_i_f, snr_i_f

# ==========================================================
# FUNZIONE PRINCIPALE: VISUALIZZAZIONE E CALCOLO METRICHE
# ==========================================================
def main_visualization(input_file_path, filtered_file_path):
    global gray_scale_image_matrix, filtered_image_project

    # Caricamento immagini da file TXT
    gray_scale_image_matrix = read_image(input_file_path)  # Originale
    filtered_image_project = read_image(filtered_file_path)  # Filtrata

    # Calcolo valori
    psnr_val, snr_val = psnr_calculation()
    ssim_val, ssim_map, dssim_val, dssim_map = ssim_calculation()

    # Completamento visualizzazione
    plt.subplot(2, 2, 1)
    plt.imshow(gray_scale_image_matrix, cmap='gray', vmin=0, vmax=255)
    plt.title("Immagine Originale")
    plt.colorbar()

    plt.tight_layout()
    plt.show()

    # Stampa valori calcolati in console
    print(f"PSNR: {psnr_val:.2f}")
    print(f"SNR: {snr_val:.2f}")
    print(f"SSIM: {ssim_val:.4f}")
    print(f"DSSIM: {dssim_val:.4f}")

# ==========================================================
# CHIAMATA FINALE PER ESEGUIRE TUTTO
# ==========================================================
# Chiama main_visualization per caricare immagini, calcolare metriche e visualizzare
main_visualization(input_file_path, file_path_VHDL)